// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/StewardMcCormick/go-job-queue/gen/go/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// PublishCreateEvent provides a mock function for the type MockTaskService
func (_mock *MockTaskService) PublishCreateEvent(ctx context.Context, req *jobqueue.Task) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PublishCreateEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *jobqueue.Task) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskService_PublishCreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCreateEvent'
type MockTaskService_PublishCreateEvent_Call struct {
	*mock.Call
}

// PublishCreateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - req *jobqueue.Task
func (_e *MockTaskService_Expecter) PublishCreateEvent(ctx interface{}, req interface{}) *MockTaskService_PublishCreateEvent_Call {
	return &MockTaskService_PublishCreateEvent_Call{Call: _e.mock.On("PublishCreateEvent", ctx, req)}
}

func (_c *MockTaskService_PublishCreateEvent_Call) Run(run func(ctx context.Context, req *jobqueue.Task)) *MockTaskService_PublishCreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *jobqueue.Task
		if args[1] != nil {
			arg1 = args[1].(*jobqueue.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_PublishCreateEvent_Call) Return(err error) *MockTaskService_PublishCreateEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskService_PublishCreateEvent_Call) RunAndReturn(run func(ctx context.Context, req *jobqueue.Task) error) *MockTaskService_PublishCreateEvent_Call {
	_c.Call.Return(run)
	return _c
}
